### ISSUE TITLE
Option to use environment variable in the plugin

### ISSUE THREAD

**Issue by chalapathy** [jenkinsci/accelq-ci-connect-plugin#6]
### Feature Request
Hi Team,
I have a request.
Generally In Jenkins the post-build Actions will be able to read the environment variables if we define it as ${name-of-the-variable}. I want a similar option in AccelQ plugin as well because we want to provide an interface to the user where the AccelQ Job ID will be the only input and we should be able to substitute that parameter in "ACCELQ CI Job ID"
I want all the parameters of the plugin configurable with the variables.

If this feature is already present please let me know how to substitute it

Thanks
Chalapathy J

**Comment by accelq** [comment]
Since in Jenkins the input fields does not work with both environment variables and text based values, it gets tricky to resolve this as of now. You can use our script based route which allows using env variables. The link to it is attached below.
https://support.accelq.com/hc/en-us/articles/360046404991-Running-ACCELQ-Tests-using-Scripts
